TEST_FORECAST = {
    "cod": "200",
    "message": 0,
    "cnt": 40,
    "list": [
        {
            "dt": 1649862000,
            "main": {
                "temp": 68.52,
                "feels_like": 68.27,
                "temp_min": 68.52,
                "temp_max": 70.27,
                "pressure": 1016,
                "sea_level": 1016,
                "grnd_level": 990,
                "humidity": 68,
                "temp_kf": -0.97,
            },
            "weather": [
                {
                    "id": 803,
                    "main": "Clouds",
                    "description": "broken clouds",
                    "icon": "04d",
                }
            ],
            "clouds": {"all": 81},
            "wind": {"speed": 13.02, "deg": 169, "gust": 26.96},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "d"},
            "dt_txt": "2022-04-13 15:00:00",
        },
        {
            "dt": 1649872800,
            "main": {
                "temp": 74.52,
                "feels_like": 74.3,
                "temp_min": 74.52,
                "temp_max": 77.95,
                "pressure": 1014,
                "sea_level": 1014,
                "grnd_level": 989,
                "humidity": 56,
                "temp_kf": -1.91,
            },
            "weather": [
                {
                    "id": 804,
                    "main": "Clouds",
                    "description": "overcast clouds",
                    "icon": "04d",
                }
            ],
            "clouds": {"all": 87},
            "wind": {"speed": 14.38, "deg": 183, "gust": 24.79},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "d"},
            "dt_txt": "2022-04-13 18:00:00",
        },
        {
            "dt": 1649883600,
            "main": {
                "temp": 79.63,
                "feels_like": 79.63,
                "temp_min": 79.63,
                "temp_max": 79.63,
                "pressure": 1011,
                "sea_level": 1011,
                "grnd_level": 986,
                "humidity": 50,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 803,
                    "main": "Clouds",
                    "description": "broken clouds",
                    "icon": "04d",
                }
            ],
            "clouds": {"all": 69},
            "wind": {"speed": 12.88, "deg": 187, "gust": 27.81},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "d"},
            "dt_txt": "2022-04-13 21:00:00",
        },
        {
            "dt": 1649894400,
            "main": {
                "temp": 71.55,
                "feels_like": 71.51,
                "temp_min": 71.55,
                "temp_max": 71.55,
                "pressure": 1011,
                "sea_level": 1011,
                "grnd_level": 986,
                "humidity": 66,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 803,
                    "main": "Clouds",
                    "description": "broken clouds",
                    "icon": "04d",
                }
            ],
            "clouds": {"all": 54},
            "wind": {"speed": 11.03, "deg": 186, "gust": 26.75},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "d"},
            "dt_txt": "2022-04-14 00:00:00",
        },
        {
            "dt": 1649905200,
            "main": {
                "temp": 68.31,
                "feels_like": 68.31,
                "temp_min": 68.31,
                "temp_max": 68.31,
                "pressure": 1010,
                "sea_level": 1010,
                "grnd_level": 985,
                "humidity": 74,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 803,
                    "main": "Clouds",
                    "description": "broken clouds",
                    "icon": "04n",
                }
            ],
            "clouds": {"all": 74},
            "wind": {"speed": 13.69, "deg": 188, "gust": 37.13},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "n"},
            "dt_txt": "2022-04-14 03:00:00",
        },
        {
            "dt": 1649916000,
            "main": {
                "temp": 63.55,
                "feels_like": 64.17,
                "temp_min": 63.55,
                "temp_max": 63.55,
                "pressure": 1011,
                "sea_level": 1011,
                "grnd_level": 986,
                "humidity": 97,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 501,
                    "main": "Rain",
                    "description": "moderate rain",
                    "icon": "10n",
                }
            ],
            "clouds": {"all": 87},
            "wind": {"speed": 7.87, "deg": 193, "gust": 24.94},
            "visibility": 3678,
            "pop": 0.98,
            "rain": {"3h": 5.14},
            "sys": {"pod": "n"},
            "dt_txt": "2022-04-14 06:00:00",
        },
        {
            "dt": 1649926800,
            "main": {
                "temp": 61.09,
                "feels_like": 61.41,
                "temp_min": 61.09,
                "temp_max": 61.09,
                "pressure": 1012,
                "sea_level": 1012,
                "grnd_level": 987,
                "humidity": 96,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 501,
                    "main": "Rain",
                    "description": "moderate rain",
                    "icon": "10n",
                }
            ],
            "clouds": {"all": 100},
            "wind": {"speed": 9.17, "deg": 268, "gust": 20.15},
            "visibility": 9552,
            "pop": 1,
            "rain": {"3h": 7.78},
            "sys": {"pod": "n"},
            "dt_txt": "2022-04-14 09:00:00",
        },
        {
            "dt": 1649937600,
            "main": {
                "temp": 51.33,
                "feels_like": 50.54,
                "temp_min": 51.33,
                "temp_max": 51.33,
                "pressure": 1016,
                "sea_level": 1016,
                "grnd_level": 990,
                "humidity": 93,
                "temp_kf": 0,
            },
            "weather": [
                {"id": 500, "main": "Rain", "description": "light rain", "icon": "10d"}
            ],
            "clouds": {"all": 100},
            "wind": {"speed": 4.43, "deg": 314, "gust": 10.85},
            "visibility": 10000,
            "pop": 1,
            "rain": {"3h": 0.56},
            "sys": {"pod": "d"},
            "dt_txt": "2022-04-14 12:00:00",
        },
        {
            "dt": 1649948400,
            "main": {
                "temp": 58.87,
                "feels_like": 57.29,
                "temp_min": 58.87,
                "temp_max": 58.87,
                "pressure": 1017,
                "sea_level": 1017,
                "grnd_level": 992,
                "humidity": 60,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 803,
                    "main": "Clouds",
                    "description": "broken clouds",
                    "icon": "04d",
                }
            ],
            "clouds": {"all": 57},
            "wind": {"speed": 3.98, "deg": 348, "gust": 5.46},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "d"},
            "dt_txt": "2022-04-14 15:00:00",
        },
        {
            "dt": 1649959200,
            "main": {
                "temp": 69.93,
                "feels_like": 68.22,
                "temp_min": 69.93,
                "temp_max": 69.93,
                "pressure": 1016,
                "sea_level": 1016,
                "grnd_level": 991,
                "humidity": 34,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 802,
                    "main": "Clouds",
                    "description": "scattered clouds",
                    "icon": "03d",
                }
            ],
            "clouds": {"all": 29},
            "wind": {"speed": 3.65, "deg": 316, "gust": 5.82},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "d"},
            "dt_txt": "2022-04-14 18:00:00",
        },
        {
            "dt": 1649970000,
            "main": {
                "temp": 69.04,
                "feels_like": 67.21,
                "temp_min": 69.04,
                "temp_max": 69.04,
                "pressure": 1015,
                "sea_level": 1015,
                "grnd_level": 990,
                "humidity": 33,
                "temp_kf": 0,
            },
            "weather": [
                {"id": 800, "main": "Clear", "description": "clear sky", "icon": "01d"}
            ],
            "clouds": {"all": 0},
            "wind": {"speed": 10.27, "deg": 298, "gust": 10.38},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "d"},
            "dt_txt": "2022-04-14 21:00:00",
        },
        {
            "dt": 1649980800,
            "main": {
                "temp": 56.1,
                "feels_like": 54.19,
                "temp_min": 56.1,
                "temp_max": 56.1,
                "pressure": 1018,
                "sea_level": 1018,
                "grnd_level": 992,
                "humidity": 59,
                "temp_kf": 0,
            },
            "weather": [
                {"id": 800, "main": "Clear", "description": "clear sky", "icon": "01d"}
            ],
            "clouds": {"all": 1},
            "wind": {"speed": 5.91, "deg": 324, "gust": 16.04},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "d"},
            "dt_txt": "2022-04-15 00:00:00",
        },
        {
            "dt": 1649991600,
            "main": {
                "temp": 48.24,
                "feels_like": 48.24,
                "temp_min": 48.24,
                "temp_max": 48.24,
                "pressure": 1021,
                "sea_level": 1021,
                "grnd_level": 995,
                "humidity": 71,
                "temp_kf": 0,
            },
            "weather": [
                {"id": 800, "main": "Clear", "description": "clear sky", "icon": "01n"}
            ],
            "clouds": {"all": 1},
            "wind": {"speed": 2.26, "deg": 345, "gust": 2.62},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "n"},
            "dt_txt": "2022-04-15 03:00:00",
        },
        {
            "dt": 1650002400,
            "main": {
                "temp": 45.45,
                "feels_like": 44.26,
                "temp_min": 45.45,
                "temp_max": 45.45,
                "pressure": 1022,
                "sea_level": 1022,
                "grnd_level": 996,
                "humidity": 74,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 801,
                    "main": "Clouds",
                    "description": "few clouds",
                    "icon": "02n",
                }
            ],
            "clouds": {"all": 17},
            "wind": {"speed": 3.27, "deg": 354, "gust": 3.67},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "n"},
            "dt_txt": "2022-04-15 06:00:00",
        },
        {
            "dt": 1650013200,
            "main": {
                "temp": 43.29,
                "feels_like": 41.65,
                "temp_min": 43.29,
                "temp_max": 43.29,
                "pressure": 1022,
                "sea_level": 1022,
                "grnd_level": 996,
                "humidity": 76,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 803,
                    "main": "Clouds",
                    "description": "broken clouds",
                    "icon": "04n",
                }
            ],
            "clouds": {"all": 56},
            "wind": {"speed": 3.42, "deg": 43, "gust": 4.21},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "n"},
            "dt_txt": "2022-04-15 09:00:00",
        },
        {
            "dt": 1650024000,
            "main": {
                "temp": 44.6,
                "feels_like": 44.6,
                "temp_min": 44.6,
                "temp_max": 44.6,
                "pressure": 1022,
                "sea_level": 1022,
                "grnd_level": 996,
                "humidity": 74,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 803,
                    "main": "Clouds",
                    "description": "broken clouds",
                    "icon": "04d",
                }
            ],
            "clouds": {"all": 59},
            "wind": {"speed": 2.73, "deg": 4, "gust": 6.2},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "d"},
            "dt_txt": "2022-04-15 12:00:00",
        },
        {
            "dt": 1650034800,
            "main": {
                "temp": 60.89,
                "feels_like": 58.51,
                "temp_min": 60.89,
                "temp_max": 60.89,
                "pressure": 1022,
                "sea_level": 1022,
                "grnd_level": 996,
                "humidity": 39,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 803,
                    "main": "Clouds",
                    "description": "broken clouds",
                    "icon": "04d",
                }
            ],
            "clouds": {"all": 59},
            "wind": {"speed": 3.49, "deg": 104, "gust": 5.37},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "d"},
            "dt_txt": "2022-04-15 15:00:00",
        },
        {
            "dt": 1650045600,
            "main": {
                "temp": 70.41,
                "feels_like": 68.7,
                "temp_min": 70.41,
                "temp_max": 70.41,
                "pressure": 1019,
                "sea_level": 1019,
                "grnd_level": 994,
                "humidity": 33,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 803,
                    "main": "Clouds",
                    "description": "broken clouds",
                    "icon": "04d",
                }
            ],
            "clouds": {"all": 63},
            "wind": {"speed": 8.72, "deg": 159, "gust": 13.44},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "d"},
            "dt_txt": "2022-04-15 18:00:00",
        },
        {
            "dt": 1650056400,
            "main": {
                "temp": 74.52,
                "feels_like": 73.17,
                "temp_min": 74.52,
                "temp_max": 74.52,
                "pressure": 1017,
                "sea_level": 1017,
                "grnd_level": 992,
                "humidity": 32,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 803,
                    "main": "Clouds",
                    "description": "broken clouds",
                    "icon": "04d",
                }
            ],
            "clouds": {"all": 77},
            "wind": {"speed": 9.57, "deg": 180, "gust": 15.97},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "d"},
            "dt_txt": "2022-04-15 21:00:00",
        },
        {
            "dt": 1650067200,
            "main": {
                "temp": 62.24,
                "feels_like": 61.32,
                "temp_min": 62.24,
                "temp_max": 62.24,
                "pressure": 1017,
                "sea_level": 1017,
                "grnd_level": 992,
                "humidity": 67,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 803,
                    "main": "Clouds",
                    "description": "broken clouds",
                    "icon": "04d",
                }
            ],
            "clouds": {"all": 53},
            "wind": {"speed": 3.6, "deg": 183, "gust": 3.78},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "d"},
            "dt_txt": "2022-04-16 00:00:00",
        },
        {
            "dt": 1650078000,
            "main": {
                "temp": 55.49,
                "feels_like": 54.41,
                "temp_min": 55.49,
                "temp_max": 55.49,
                "pressure": 1018,
                "sea_level": 1018,
                "grnd_level": 993,
                "humidity": 78,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 802,
                    "main": "Clouds",
                    "description": "scattered clouds",
                    "icon": "03n",
                }
            ],
            "clouds": {"all": 30},
            "wind": {"speed": 2.82, "deg": 174, "gust": 2.86},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "n"},
            "dt_txt": "2022-04-16 03:00:00",
        },
        {
            "dt": 1650088800,
            "main": {
                "temp": 52.9,
                "feels_like": 51.89,
                "temp_min": 52.9,
                "temp_max": 52.9,
                "pressure": 1018,
                "sea_level": 1018,
                "grnd_level": 993,
                "humidity": 85,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 802,
                    "main": "Clouds",
                    "description": "scattered clouds",
                    "icon": "03n",
                }
            ],
            "clouds": {"all": 40},
            "wind": {"speed": 2.13, "deg": 165, "gust": 2.37},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "n"},
            "dt_txt": "2022-04-16 06:00:00",
        },
        {
            "dt": 1650099600,
            "main": {
                "temp": 55.92,
                "feels_like": 54.84,
                "temp_min": 55.92,
                "temp_max": 55.92,
                "pressure": 1018,
                "sea_level": 1018,
                "grnd_level": 992,
                "humidity": 77,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 803,
                    "main": "Clouds",
                    "description": "broken clouds",
                    "icon": "04n",
                }
            ],
            "clouds": {"all": 79},
            "wind": {"speed": 2.77, "deg": 138, "gust": 3.58},
            "visibility": 10000,
            "pop": 0.01,
            "sys": {"pod": "n"},
            "dt_txt": "2022-04-16 09:00:00",
        },
        {
            "dt": 1650110400,
            "main": {
                "temp": 56.55,
                "feels_like": 56.37,
                "temp_min": 56.55,
                "temp_max": 56.55,
                "pressure": 1019,
                "sea_level": 1019,
                "grnd_level": 993,
                "humidity": 95,
                "temp_kf": 0,
            },
            "weather": [
                {"id": 500, "main": "Rain", "description": "light rain", "icon": "10d"}
            ],
            "clouds": {"all": 89},
            "wind": {"speed": 1.9, "deg": 192, "gust": 4.05},
            "visibility": 10000,
            "pop": 0.97,
            "rain": {"3h": 2.08},
            "sys": {"pod": "d"},
            "dt_txt": "2022-04-16 12:00:00",
        },
        {
            "dt": 1650121200,
            "main": {
                "temp": 63.19,
                "feels_like": 62.92,
                "temp_min": 63.19,
                "temp_max": 63.19,
                "pressure": 1019,
                "sea_level": 1019,
                "grnd_level": 994,
                "humidity": 79,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 804,
                    "main": "Clouds",
                    "description": "overcast clouds",
                    "icon": "04d",
                }
            ],
            "clouds": {"all": 98},
            "wind": {"speed": 4.12, "deg": 199, "gust": 7.23},
            "visibility": 10000,
            "pop": 0.31,
            "sys": {"pod": "d"},
            "dt_txt": "2022-04-16 15:00:00",
        },
        {
            "dt": 1650132000,
            "main": {
                "temp": 70.21,
                "feels_like": 70.18,
                "temp_min": 70.21,
                "temp_max": 70.21,
                "pressure": 1018,
                "sea_level": 1018,
                "grnd_level": 993,
                "humidity": 69,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 804,
                    "main": "Clouds",
                    "description": "overcast clouds",
                    "icon": "04d",
                }
            ],
            "clouds": {"all": 98},
            "wind": {"speed": 2.86, "deg": 238, "gust": 3.78},
            "visibility": 10000,
            "pop": 0.16,
            "sys": {"pod": "d"},
            "dt_txt": "2022-04-16 18:00:00",
        },
        {
            "dt": 1650142800,
            "main": {
                "temp": 70.45,
                "feels_like": 70.63,
                "temp_min": 70.45,
                "temp_max": 70.45,
                "pressure": 1017,
                "sea_level": 1017,
                "grnd_level": 992,
                "humidity": 73,
                "temp_kf": 0,
            },
            "weather": [
                {"id": 500, "main": "Rain", "description": "light rain", "icon": "10d"}
            ],
            "clouds": {"all": 99},
            "wind": {"speed": 5.44, "deg": 282, "gust": 8.23},
            "visibility": 10000,
            "pop": 0.58,
            "rain": {"3h": 0.34},
            "sys": {"pod": "d"},
            "dt_txt": "2022-04-16 21:00:00",
        },
        {
            "dt": 1650153600,
            "main": {
                "temp": 62.62,
                "feels_like": 62.91,
                "temp_min": 62.62,
                "temp_max": 62.62,
                "pressure": 1018,
                "sea_level": 1018,
                "grnd_level": 992,
                "humidity": 92,
                "temp_kf": 0,
            },
            "weather": [
                {"id": 500, "main": "Rain", "description": "light rain", "icon": "10d"}
            ],
            "clouds": {"all": 99},
            "wind": {"speed": 2.28, "deg": 274, "gust": 2.13},
            "visibility": 10000,
            "pop": 1,
            "rain": {"3h": 2.07},
            "sys": {"pod": "d"},
            "dt_txt": "2022-04-17 00:00:00",
        },
        {
            "dt": 1650164400,
            "main": {
                "temp": 58.95,
                "feels_like": 59.11,
                "temp_min": 58.95,
                "temp_max": 58.95,
                "pressure": 1019,
                "sea_level": 1019,
                "grnd_level": 993,
                "humidity": 97,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 804,
                    "main": "Clouds",
                    "description": "overcast clouds",
                    "icon": "04n",
                }
            ],
            "clouds": {"all": 100},
            "wind": {"speed": 3.8, "deg": 356, "gust": 4.43},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "n"},
            "dt_txt": "2022-04-17 03:00:00",
        },
        {
            "dt": 1650175200,
            "main": {
                "temp": 56.28,
                "feels_like": 56.21,
                "temp_min": 56.28,
                "temp_max": 56.28,
                "pressure": 1018,
                "sea_level": 1018,
                "grnd_level": 993,
                "humidity": 98,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 804,
                    "main": "Clouds",
                    "description": "overcast clouds",
                    "icon": "04n",
                }
            ],
            "clouds": {"all": 100},
            "wind": {"speed": 4.92, "deg": 19, "gust": 13.94},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "n"},
            "dt_txt": "2022-04-17 06:00:00",
        },
        {
            "dt": 1650186000,
            "main": {
                "temp": 53.91,
                "feels_like": 53.56,
                "temp_min": 53.91,
                "temp_max": 53.91,
                "pressure": 1018,
                "sea_level": 1018,
                "grnd_level": 992,
                "humidity": 97,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 804,
                    "main": "Clouds",
                    "description": "overcast clouds",
                    "icon": "04n",
                }
            ],
            "clouds": {"all": 100},
            "wind": {"speed": 5.66, "deg": 26, "gust": 17.87},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "n"},
            "dt_txt": "2022-04-17 09:00:00",
        },
        {
            "dt": 1650196800,
            "main": {
                "temp": 53.04,
                "feels_like": 52.41,
                "temp_min": 53.04,
                "temp_max": 53.04,
                "pressure": 1019,
                "sea_level": 1019,
                "grnd_level": 993,
                "humidity": 93,
                "temp_kf": 0,
            },
            "weather": [
                {"id": 500, "main": "Rain", "description": "light rain", "icon": "10d"}
            ],
            "clouds": {"all": 100},
            "wind": {"speed": 5.97, "deg": 28, "gust": 18.07},
            "visibility": 10000,
            "pop": 0.29,
            "rain": {"3h": 0.35},
            "sys": {"pod": "d"},
            "dt_txt": "2022-04-17 12:00:00",
        },
        {
            "dt": 1650207600,
            "main": {
                "temp": 54.99,
                "feels_like": 54.32,
                "temp_min": 54.99,
                "temp_max": 54.99,
                "pressure": 1019,
                "sea_level": 1019,
                "grnd_level": 994,
                "humidity": 88,
                "temp_kf": 0,
            },
            "weather": [
                {"id": 500, "main": "Rain", "description": "light rain", "icon": "10d"}
            ],
            "clouds": {"all": 100},
            "wind": {"speed": 4.36, "deg": 47, "gust": 7.49},
            "visibility": 10000,
            "pop": 0.76,
            "rain": {"3h": 1.17},
            "sys": {"pod": "d"},
            "dt_txt": "2022-04-17 15:00:00",
        },
        {
            "dt": 1650218400,
            "main": {
                "temp": 59.9,
                "feels_like": 59.63,
                "temp_min": 59.9,
                "temp_max": 59.9,
                "pressure": 1017,
                "sea_level": 1017,
                "grnd_level": 992,
                "humidity": 86,
                "temp_kf": 0,
            },
            "weather": [
                {"id": 500, "main": "Rain", "description": "light rain", "icon": "10d"}
            ],
            "clouds": {"all": 100},
            "wind": {"speed": 2.71, "deg": 74, "gust": 3.62},
            "visibility": 10000,
            "pop": 0.97,
            "rain": {"3h": 0.84},
            "sys": {"pod": "d"},
            "dt_txt": "2022-04-17 18:00:00",
        },
        {
            "dt": 1650229200,
            "main": {
                "temp": 61.52,
                "feels_like": 61.7,
                "temp_min": 61.52,
                "temp_max": 61.52,
                "pressure": 1015,
                "sea_level": 1015,
                "grnd_level": 990,
                "humidity": 92,
                "temp_kf": 0,
            },
            "weather": [
                {"id": 500, "main": "Rain", "description": "light rain", "icon": "10d"}
            ],
            "clouds": {"all": 100},
            "wind": {"speed": 2.46, "deg": 143, "gust": 7.4},
            "visibility": 10000,
            "pop": 0.99,
            "rain": {"3h": 0.77},
            "sys": {"pod": "d"},
            "dt_txt": "2022-04-17 21:00:00",
        },
        {
            "dt": 1650240000,
            "main": {
                "temp": 60.75,
                "feels_like": 61.12,
                "temp_min": 60.75,
                "temp_max": 60.75,
                "pressure": 1015,
                "sea_level": 1015,
                "grnd_level": 989,
                "humidity": 98,
                "temp_kf": 0,
            },
            "weather": [
                {"id": 500, "main": "Rain", "description": "light rain", "icon": "10d"}
            ],
            "clouds": {"all": 100},
            "wind": {"speed": 2.68, "deg": 164, "gust": 5.48},
            "visibility": 7614,
            "pop": 1,
            "rain": {"3h": 1.8},
            "sys": {"pod": "d"},
            "dt_txt": "2022-04-18 00:00:00",
        },
        {
            "dt": 1650250800,
            "main": {
                "temp": 61.27,
                "feels_like": 61.7,
                "temp_min": 61.27,
                "temp_max": 61.27,
                "pressure": 1014,
                "sea_level": 1014,
                "grnd_level": 989,
                "humidity": 98,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 501,
                    "main": "Rain",
                    "description": "moderate rain",
                    "icon": "10n",
                }
            ],
            "clouds": {"all": 100},
            "wind": {"speed": 4.47, "deg": 151, "gust": 20.04},
            "visibility": 10000,
            "pop": 1,
            "rain": {"3h": 4.86},
            "sys": {"pod": "n"},
            "dt_txt": "2022-04-18 03:00:00",
        },
        {
            "dt": 1650261600,
            "main": {
                "temp": 60.75,
                "feels_like": 61.18,
                "temp_min": 60.75,
                "temp_max": 60.75,
                "pressure": 1013,
                "sea_level": 1013,
                "grnd_level": 988,
                "humidity": 99,
                "temp_kf": 0,
            },
            "weather": [
                {"id": 500, "main": "Rain", "description": "light rain", "icon": "10n"}
            ],
            "clouds": {"all": 100},
            "wind": {"speed": 5.06, "deg": 182, "gust": 19.51},
            "visibility": 4591,
            "pop": 1,
            "rain": {"3h": 1.08},
            "sys": {"pod": "n"},
            "dt_txt": "2022-04-18 06:00:00",
        },
        {
            "dt": 1650272400,
            "main": {
                "temp": 60.62,
                "feels_like": 61.03,
                "temp_min": 60.62,
                "temp_max": 60.62,
                "pressure": 1013,
                "sea_level": 1013,
                "grnd_level": 988,
                "humidity": 99,
                "temp_kf": 0,
            },
            "weather": [
                {"id": 500, "main": "Rain", "description": "light rain", "icon": "10n"}
            ],
            "clouds": {"all": 99},
            "wind": {"speed": 3.71, "deg": 208, "gust": 13.73},
            "visibility": 8167,
            "pop": 1,
            "rain": {"3h": 1.88},
            "sys": {"pod": "n"},
            "dt_txt": "2022-04-18 09:00:00",
        },
        {
            "dt": 1650283200,
            "main": {
                "temp": 60.55,
                "feels_like": 60.96,
                "temp_min": 60.55,
                "temp_max": 60.55,
                "pressure": 1015,
                "sea_level": 1015,
                "grnd_level": 989,
                "humidity": 99,
                "temp_kf": 0,
            },
            "weather": [
                {"id": 500, "main": "Rain", "description": "light rain", "icon": "10d"}
            ],
            "clouds": {"all": 100},
            "wind": {"speed": 1.79, "deg": 264, "gust": 4.29},
            "visibility": 10000,
            "pop": 1,
            "rain": {"3h": 0.57},
            "sys": {"pod": "d"},
            "dt_txt": "2022-04-18 12:00:00",
        },
    ],
    "city": {
        "id": 4612862,
        "name": "Chattanooga",
        "coord": {"lat": 35.0456, "lon": -85.3097},
        "country": "US",
        "population": 167674,
        "timezone": -14400,
        "sunrise": 1649848292,
        "sunset": 1649895090,
    },
}

TEST_BASE = {
    "coord": {"lon": -85.3097, "lat": 35.0456},
    "weather": [
        {"id": 803, "main": "Clouds", "description": "broken clouds", "icon": "04d"}
    ],
    "base": "stations",
    "main": {
        "temp": 72.32,
        "feels_like": 72.3,
        "temp_min": 70.41,
        "temp_max": 74.25,
        "pressure": 1014,
        "humidity": 65,
    },
    "visibility": 10000,
    "wind": {"speed": 10.36, "deg": 180, "gust": 24.16},
    "clouds": {"all": 75},
    "dt": 1649863853,
    "sys": {
        "type": 2,
        "id": 2041352,
        "country": "US",
        "sunrise": 1649848292,
        "sunset": 1649895090,
    },
    "timezone": -14400,
    "id": 4612862,
    "name": "Chattanooga",
    "cod": 200,
}
